version: '3'
services:
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=localhost
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
